# fill base_dir with a personal absolute path
base_dir: "/home/marta/airline-passenger-prediction-using-LSTMs/"

# data sets
raw_data: "data/raw/international-airline-passengers.csv"
interim_data: "data/interim/international-airline-passengers.csv"
processed_data: "data/processed/international-airline-passengers.csv"

# tuning logs and trained models
models: "output/models/"

# scores
scores: "output/scores.csv"

# visulizations
plots: "output/"